### ISSUE TITLE
Missing Description 

### ISSUE THREAD

**Issue by ajeetk1** [PacktPublishing/50-Projects-In-50-Days---HTML-CSS-JavaScript#3]
Can brief description be included about 50 Projects-50 Days about it so user get to  know about it before checking code base or live demo?

**Comment by Sonakshis** [comment]
Hi, 
Thank you so much for your feedback! 
The names of all the 50 mini-projects included in the course are present in the readme file. Here is the link to readme file: 
https://github.com/PacktPublishing/50-Projects-In-50-Days---HTML-CSS-JavaScript/blob/edc4a8ac50f21d14c2643454f3224f7d7b51ce17/README.md 

This should help you out. Do let us know in case of any further queries. 

Happy learning!
